// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countSort
SEXP countSort(SEXP unsorted, bool inplace);
RcppExport SEXP _IntegerSort_countSort(SEXP unsortedSEXP, SEXP inplaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type unsorted(unsortedSEXP);
    Rcpp::traits::input_parameter< bool >::type inplace(inplaceSEXP);
    rcpp_result_gen = Rcpp::wrap(countSort(unsorted, inplace));
    return rcpp_result_gen;
END_RCPP
}
// insertSort
SEXP insertSort(SEXP unsorted, bool inplace);
RcppExport SEXP _IntegerSort_insertSort(SEXP unsortedSEXP, SEXP inplaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type unsorted(unsortedSEXP);
    Rcpp::traits::input_parameter< bool >::type inplace(inplaceSEXP);
    rcpp_result_gen = Rcpp::wrap(insertSort(unsorted, inplace));
    return rcpp_result_gen;
END_RCPP
}
// isample
IntegerVector isample(int size);
RcppExport SEXP _IntegerSort_isample(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(isample(size));
    return rcpp_result_gen;
END_RCPP
}
// lsdSort
SEXP lsdSort(SEXP unsorted, bool inplace);
RcppExport SEXP _IntegerSort_lsdSort(SEXP unsortedSEXP, SEXP inplaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type unsorted(unsortedSEXP);
    Rcpp::traits::input_parameter< bool >::type inplace(inplaceSEXP);
    rcpp_result_gen = Rcpp::wrap(lsdSort(unsorted, inplace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IntegerSort_countSort", (DL_FUNC) &_IntegerSort_countSort, 2},
    {"_IntegerSort_insertSort", (DL_FUNC) &_IntegerSort_insertSort, 2},
    {"_IntegerSort_isample", (DL_FUNC) &_IntegerSort_isample, 1},
    {"_IntegerSort_lsdSort", (DL_FUNC) &_IntegerSort_lsdSort, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_IntegerSort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
