# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countSort <- function(unsorted, inplace = FALSE) {
    .Call(`_IntegerSort_countSort`, unsorted, inplace)
}

insertSort <- function(unsorted, inplace = FALSE) {
    .Call(`_IntegerSort_insertSort`, unsorted, inplace)
}

isample <- function(size = 1L) {
    .Call(`_IntegerSort_isample`, size)
}

lsdSort <- function(unsorted, inplace = FALSE) {
    .Call(`_IntegerSort_lsdSort`, unsorted, inplace)
}

